name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest GHH version
      uses: ./latest-gloomhaven-helper-action
      id: version

    - name: Build and push Docker images
      uses: aevea/action-kaniko@v0.5.1
      with:
        username: grepnull
        password: ${{ secrets.DOCKER_KEY }}
        image: grepnull/gloomhaven-helper-headless
        cache: true
        cache_registry: grepnull/cache
        extra_args: "--build-arg version=${{ steps.version.outputs.version }} --destination grepnull/gloomhaven-helper-headless:${{ steps.version.outputs.version }} --destination grepnull/gloomhaven-helper-headless:${{ steps.version.outputs.major }} --destination grepnull/gloomhaven-helper-headless:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"
        # skip_unchanged_digest: true ### Broken as of v0.5.1

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      if: github.ref == 'refs/heads/master'
      env:
        DOCKERHUB_USERNAME: grepnull
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: grepnull/gloomhaven-helper-headless
